// <auto-generated />
using System;
using GestionUsine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionUsine.Migrations
{
    [DbContext(typeof(GestionUsineContext))]
    partial class GestionUsineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestionUsine.Models.ChefEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("MotDePasse");

                    b.Property<string>("Nom");

                    b.Property<string>("Prenom");

                    b.HasKey("Id");

                    b.ToTable("ChefEquipe");
                });

            modelBuilder.Entity("GestionUsine.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChefEquipeId");

                    b.Property<string>("Email");

                    b.Property<string>("MotDePasse");

                    b.Property<string>("Nom");

                    b.Property<string>("Prenom");

                    b.Property<int>("RoleID");

                    b.HasKey("Id");

                    b.HasIndex("ChefEquipeId");

                    b.HasIndex("RoleID");

                    b.ToTable("Employe");
                });

            modelBuilder.Entity("GestionUsine.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomRole");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("GestionUsine.Models.SuperUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("MotDePasse");

                    b.Property<string>("Nom");

                    b.Property<string>("Prenom");

                    b.HasKey("Id");

                    b.ToTable("SuperUser");
                });

            modelBuilder.Entity("GestionUsine.Models.Employe", b =>
                {
                    b.HasOne("GestionUsine.Models.ChefEquipe")
                        .WithMany("Employes")
                        .HasForeignKey("ChefEquipeId");

                    b.HasOne("GestionUsine.Models.Role", "Role")
                        .WithMany("Employes")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
